services:
  squid:
    image: ubuntu/squid
    container_name: squid
    ports:
      - "3130:3130"
    volumes:
      - ./squid_config/squid.conf:/etc/squid/squid.conf
    restart: always
  web-pac:
    image: nginx
    container_name: web-pac
    ports:
      - "8080:80"
    volumes:
      - ./nginx_config/web:/usr/share/nginx/html
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    restart: always