server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Desactivar cache de archivos abiertos por Nginx
    open_file_cache off;

    location ~* \.pac$ {
        # MIME type correcto para archivos PAC
        types { }
        default_type application/x-ns-proxy-autoconfig;

        # Desactivar cache en el cliente
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";

        # Desactivar sendfile para que Nginx lea el archivo del disco cada vez
        sendfile off;
    }
}
